# Generated by Django 2.1 on 2024-09-22 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Song Title')),
                ('stage_name', models.CharField(default='Unknown Artist', max_length=50, verbose_name='Artist Stage Name')),
                ('release_date', models.DateField(verbose_name='Release Date')),
                ('cover_art', models.ImageField(blank=True, null=True, upload_to='release_images/', verbose_name='Cover Art')),
                ('song', models.FileField(blank=True, null=True, upload_to='release_songs/', verbose_name='Song File')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Music Release',
                'verbose_name_plural': 'Music Releases',
                'ordering': ['release_date'],
            },
        ),
    ]
