# Generated by Django 2.1 on 2024-09-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='id_user',
            field=models.IntegerField(null=True),
        ),
    ]
