# Generated by Django 2.1 on 2024-09-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_music_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='credits',
            field=models.TextField(blank=True, null=True, verbose_name='Credits'),
        ),
        migrations.AddField(
            model_name='music',
            name='featured_artists',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Featured Artists'),
        ),
        migrations.AddField(
            model_name='music',
            name='genre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Genre'),
        ),
    ]
